@startuml Book Management
package "Book Management" {
    class Book {
        -String title
        -String author
        -String ISBN
        -String genre
        -int publicationYear
    }
    
    class BooksManager {
        +ErrorHandler errorHandler
        +List<Book> books
        +BooksManager(List<Book> books)
        +void addBook(Book book)
        +void updateBook(Book book)
        +void removeBook(Book book)
    }
}
@enduml
