@startuml LibraryManagementSystem

' Define modules
    !include Reporting.puml
    !include Search.puml
    !include BorrowingSystem.puml
    !include Managers.puml
    !include Models.puml
    !include LibraryConsole.puml
    !include Exceptions.puml
    !include Validators.puml


package "Library System" {
    class Library {
        - BooksManager _booksManager
        - PatronsManager _patronsManager
        - BorrowBook _borrowBook
        - ReturnBook _returnBook
        - BorrowingOperation _borrowingOperation
        + Library()
        + patronsManager()
        + booksManager()
        + BorrowBook()
        + ReturnBook()
        + BorrowOperation()
    }
}

Library *-- BorrowBook 
Library *-- ReturnBook 
Library *-- BorrowingOperation 
Library *-- HomePage
Library *-- ReportContext
ReportContext o-- ISearchStrategy
Library o-- ISearchStrategy
Library o-- BooksManager
Library o-- PatronsManager
Patron o-- Book 
Book *-- BorrowingInfo
BooksManager *-- Book
PatronsManager *-- Patron
AManager o-- Validator 
ValidationException o-- Validator
BorrowingOperation o-- Validator
@enduml
