@startuml Search
package "Search" {
    interface ISearchStrategy<T> {
        +List<T> search(List<T> dataList)
    }

    class SearchByTitle implements ISearchStrategy {
        +String bookTitle
        +List<Book> search(List<Book> dataList)
    }

    class SearchByAuthor implements ISearchStrategy {
        +String author
        +List<Book> search(List<Book> dataList)
    }

    class SearchByISBN implements ISearchStrategy {
        +String isbn
        +List<Book> search(List<Book> dataList)
    }

    class SearchByName implements ISearchStrategy {
        +String name
        +List<Patron> search(List<Patron> dataList)
    }

    class SearchByMembershipNumber implements ISearchStrategy {
        +int membershipNumber
        +List<Patron> search(List<Patron> dataList)
    }
}
@enduml
